<?php

return [
    ['code' => '+970', 'label' => 'Palestine (+970)', 'flag' => '🇵🇸'],
    ['code' => '+972', 'label' => 'Israel (+972)', 'flag' => '🇮🇱'],
    ['code' => '+1', 'label' => 'USA / Canada (+1)', 'flag' => '🇺🇸'],
    ['code' => '+44', 'label' => 'United Kingdom (+44)', 'flag' => '🇬🇧'],
    ['code' => '+49', 'label' => 'Germany (+49)', 'flag' => '🇩🇪'],
    ['code' => '+33', 'label' => 'France (+33)', 'flag' => '🇫🇷'],
    ['code' => '+39', 'label' => 'Italy (+39)', 'flag' => '🇮🇹'],
    ['code' => '+34', 'label' => 'Spain (+34)', 'flag' => '🇪🇸'],
    ['code' => '+31', 'label' => 'Netherlands (+31)', 'flag' => '🇳🇱'],
    ['code' => '+32', 'label' => 'Belgium (+32)', 'flag' => '🇧🇪'],
    ['code' => '+41', 'label' => 'Switzerland (+41)', 'flag' => '🇨🇭'],
    ['code' => '+43', 'label' => 'Austria (+43)', 'flag' => '🇦🇹'],
    ['code' => '+46', 'label' => 'Sweden (+46)', 'flag' => '🇸🇪'],
    ['code' => '+47', 'label' => 'Norway (+47)', 'flag' => '🇳🇴'],
    ['code' => '+45', 'label' => 'Denmark (+45)', 'flag' => '🇩🇰'],
    ['code' => '+48', 'label' => 'Poland (+48)', 'flag' => '🇵🇱'],
    ['code' => '+351', 'label' => 'Portugal (+351)', 'flag' => '🇵🇹'],
    ['code' => '+353', 'label' => 'Ireland (+353)', 'flag' => '🇮🇪'],
    ['code' => '+61', 'label' => 'Australia (+61)', 'flag' => '🇦🇺'],
    ['code' => '+64', 'label' => 'New Zealand (+64)', 'flag' => '🇳🇿'],
    ['code' => '+91', 'label' => 'India (+91)', 'flag' => '🇮🇳'],
    ['code' => '+92', 'label' => 'Pakistan (+92)', 'flag' => '🇵🇰'],
    ['code' => '+971', 'label' => 'UAE (+971)', 'flag' => '🇦🇪'],
    ['code' => '+966', 'label' => 'Saudi Arabia (+966)', 'flag' => '🇸🇦'],
    ['code' => '+974', 'label' => 'Qatar (+974)', 'flag' => '🇶🇦'],
    ['code' => '+965', 'label' => 'Kuwait (+965)', 'flag' => '🇰🇼'],
    ['code' => '+973', 'label' => 'Bahrain (+973)', 'flag' => '🇧🇭'],
    ['code' => '+968', 'label' => 'Oman (+968)', 'flag' => '🇴🇲'],
    ['code' => '+962', 'label' => 'Jordan (+962)', 'flag' => '🇯🇴'],
    ['code' => '+961', 'label' => 'Lebanon (+961)', 'flag' => '🇱🇧'],
    ['code' => '+963', 'label' => 'Syria (+963)', 'flag' => '🇸🇾'],
    ['code' => '+964', 'label' => 'Iraq (+964)', 'flag' => '🇮🇶'],
    ['code' => '+20', 'label' => 'Egypt (+20)', 'flag' => '🇪🇬'],
    ['code' => '+212', 'label' => 'Morocco (+212)', 'flag' => '🇲🇦'],
    ['code' => '+213', 'label' => 'Algeria (+213)', 'flag' => '🇩🇿'],
    ['code' => '+216', 'label' => 'Tunisia (+216)', 'flag' => '🇹🇳'],
    ['code' => '+27', 'label' => 'South Africa (+27)', 'flag' => '🇿🇦'],
    ['code' => '+234', 'label' => 'Nigeria (+234)', 'flag' => '🇳🇬'],
    ['code' => '+254', 'label' => 'Kenya (+254)', 'flag' => '🇰🇪'],
    ['code' => '+55', 'label' => 'Brazil (+55)', 'flag' => '🇧🇷'],
    ['code' => '+52', 'label' => 'Mexico (+52)', 'flag' => '🇲🇽'],
    ['code' => '+54', 'label' => 'Argentina (+54)', 'flag' => '🇦🇷'],
    ['code' => '+57', 'label' => 'Colombia (+57)', 'flag' => '🇨🇴'],
    ['code' => '+81', 'label' => 'Japan (+81)', 'flag' => '🇯🇵'],
    ['code' => '+82', 'label' => 'South Korea (+82)', 'flag' => '🇰🇷'],
    ['code' => '+86', 'label' => 'China (+86)', 'flag' => '🇨🇳'],
    ['code' => '+65', 'label' => 'Singapore (+65)', 'flag' => '🇸🇬'],
    ['code' => '+60', 'label' => 'Malaysia (+60)', 'flag' => '🇲🇾'],
    ['code' => '+62', 'label' => 'Indonesia (+62)', 'flag' => '🇮🇩'],
    ['code' => '+90', 'label' => 'Turkey (+90)', 'flag' => '🇹🇷'],
    ['code' => '+7', 'label' => 'Russia (+7)', 'flag' => '🇷🇺'],
    ['code' => '+380', 'label' => 'Ukraine (+380)', 'flag' => '🇺🇦'],
];
